blank_issues_enabled: false

contact_links:
  - name: June Programming Language
    url: https://github.com/djoezeke/June
    about: Modern Scripting Language.

  - name: June Discussions 💖
    url: https://github.com/djoezeke/June/discussions
    about: The "Discussions" forum is where you want to start.

  - name: June Issues | Bug Bounty 🐞
    url: https://github.com/djoezeke/June/issues
    about: Please report issues and vulnerabilities here.

  - name: June Releases
    url: https://github.com/djoezeke/June/releases
    about: Please latest June release here.
